server:
  port: 8081

spring.config.import: "configserver:"  # Pull config from config server
spring.cloud.config.uri: http://localhost:7090  # Location of config server

spring:
  application:
    name: api-gateway

